export default data = [
  {
    Id: 1,
    author: "Hassan Ibrahim",
    title: "title testing",
    createdAt: new Date.now(),
    body: "## Testing main man service",
    comments: [],
    likes: 0,
  },
  {
    Id: 2,
    author: "Hassan Ibrahim",
    title: "title testing",
    createdAt: new Date.now(),
    body: "## Testing main man service",
    comments: [],
    likes: 0,
  },
  {
    Id: 3,
    author: "Hassan Ibrahim",
    title: "title testing",
    createdAt: new Date.now(),
    body: "## Testing main man service",
    comments: [],
    likes: 0,
  },
  {
    Id: 5,
    author: "Hassan Ibrahim",
    title: "title testing",
    createdAt: new Date.now(),
    body: "## Testing main man service",
    comments: [],
    likes: 0,
  },
  {
    Id: 4,
    author: "Hassan Ibrahim",
    title: "title testing",
    createdAt: new Date.now(),
    body: "## Testing main man service",
    comments: [],
    likes: 0,
  },
];
